/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedDevicesRouteImport } from './routes/_authenticated/devices'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiPublicStateRouteImport } from './routes/api/public/state'
import { Route as ApiPublicPairStatusRouteImport } from './routes/api/public/pair-status'
import { Route as ApiPublicIngestRouteImport } from './routes/api/public/ingest'
import { Route as ApiPublicFirmwareManifestRouteImport } from './routes/api/public/firmware-manifest'
import { Route as ApiPublicConfigRouteImport } from './routes/api/public/config'
import { Route as ApiPublicClaimRouteImport } from './routes/api/public/claim'
import { Route as AuthenticatedSensorsNewRouteImport } from './routes/_authenticated/sensors.new'
import { Route as AuthenticatedSensorsSensorIdEditRouteImport } from './routes/_authenticated/sensors.$sensorId.edit'
import { Route as AuthenticatedDevicesDeviceIdRegisterRouteImport } from './routes/_authenticated/devices.$deviceId.register'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevicesRoute = AuthenticatedDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicStateRoute = ApiPublicStateRouteImport.update({
  id: '/api/public/state',
  path: '/api/public/state',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPairStatusRoute = ApiPublicPairStatusRouteImport.update({
  id: '/api/public/pair-status',
  path: '/api/public/pair-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIngestRoute = ApiPublicIngestRouteImport.update({
  id: '/api/public/ingest',
  path: '/api/public/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFirmwareManifestRoute =
  ApiPublicFirmwareManifestRouteImport.update({
    id: '/api/public/firmware-manifest',
    path: '/api/public/firmware-manifest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConfigRoute = ApiPublicConfigRouteImport.update({
  id: '/api/public/config',
  path: '/api/public/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClaimRoute = ApiPublicClaimRouteImport.update({
  id: '/api/public/claim',
  path: '/api/public/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSensorsNewRoute = AuthenticatedSensorsNewRouteImport.update({
  id: '/sensors/new',
  path: '/sensors/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSensorsSensorIdEditRoute =
  AuthenticatedSensorsSensorIdEditRouteImport.update({
    id: '/sensors/$sensorId/edit',
    path: '/sensors/$sensorId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevicesDeviceIdRegisterRoute =
  AuthenticatedDevicesDeviceIdRegisterRouteImport.update({
    id: '/$deviceId/register',
    path: '/$deviceId/register',
    getParentRoute: () => AuthenticatedDevicesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/setup': typeof AuthenticatedSetupRoute
  '/sensors/new': typeof AuthenticatedSensorsNewRoute
  '/api/public/claim': typeof ApiPublicClaimRoute
  '/api/public/config': typeof ApiPublicConfigRoute
  '/api/public/firmware-manifest': typeof ApiPublicFirmwareManifestRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/pair-status': typeof ApiPublicPairStatusRoute
  '/api/public/state': typeof ApiPublicStateRoute
  '/devices/$deviceId/register': typeof AuthenticatedDevicesDeviceIdRegisterRoute
  '/sensors/$sensorId/edit': typeof AuthenticatedSensorsSensorIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/setup': typeof AuthenticatedSetupRoute
  '/sensors/new': typeof AuthenticatedSensorsNewRoute
  '/api/public/claim': typeof ApiPublicClaimRoute
  '/api/public/config': typeof ApiPublicConfigRoute
  '/api/public/firmware-manifest': typeof ApiPublicFirmwareManifestRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/pair-status': typeof ApiPublicPairStatusRoute
  '/api/public/state': typeof ApiPublicStateRoute
  '/devices/$deviceId/register': typeof AuthenticatedDevicesDeviceIdRegisterRoute
  '/sensors/$sensorId/edit': typeof AuthenticatedSensorsSensorIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/devices': typeof AuthenticatedDevicesRouteWithChildren
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/sensors/new': typeof AuthenticatedSensorsNewRoute
  '/api/public/claim': typeof ApiPublicClaimRoute
  '/api/public/config': typeof ApiPublicConfigRoute
  '/api/public/firmware-manifest': typeof ApiPublicFirmwareManifestRoute
  '/api/public/ingest': typeof ApiPublicIngestRoute
  '/api/public/pair-status': typeof ApiPublicPairStatusRoute
  '/api/public/state': typeof ApiPublicStateRoute
  '/_authenticated/devices/$deviceId/register': typeof AuthenticatedDevicesDeviceIdRegisterRoute
  '/_authenticated/sensors/$sensorId/edit': typeof AuthenticatedSensorsSensorIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/devices'
    | '/setup'
    | '/sensors/new'
    | '/api/public/claim'
    | '/api/public/config'
    | '/api/public/firmware-manifest'
    | '/api/public/ingest'
    | '/api/public/pair-status'
    | '/api/public/state'
    | '/devices/$deviceId/register'
    | '/sensors/$sensorId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/devices'
    | '/setup'
    | '/sensors/new'
    | '/api/public/claim'
    | '/api/public/config'
    | '/api/public/firmware-manifest'
    | '/api/public/ingest'
    | '/api/public/pair-status'
    | '/api/public/state'
    | '/devices/$deviceId/register'
    | '/sensors/$sensorId/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/devices'
    | '/_authenticated/setup'
    | '/_authenticated/sensors/new'
    | '/api/public/claim'
    | '/api/public/config'
    | '/api/public/firmware-manifest'
    | '/api/public/ingest'
    | '/api/public/pair-status'
    | '/api/public/state'
    | '/_authenticated/devices/$deviceId/register'
    | '/_authenticated/sensors/$sensorId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicClaimRoute: typeof ApiPublicClaimRoute
  ApiPublicConfigRoute: typeof ApiPublicConfigRoute
  ApiPublicFirmwareManifestRoute: typeof ApiPublicFirmwareManifestRoute
  ApiPublicIngestRoute: typeof ApiPublicIngestRoute
  ApiPublicPairStatusRoute: typeof ApiPublicPairStatusRoute
  ApiPublicStateRoute: typeof ApiPublicStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices': {
      id: '/_authenticated/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AuthenticatedDevicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/state': {
      id: '/api/public/state'
      path: '/api/public/state'
      fullPath: '/api/public/state'
      preLoaderRoute: typeof ApiPublicStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pair-status': {
      id: '/api/public/pair-status'
      path: '/api/public/pair-status'
      fullPath: '/api/public/pair-status'
      preLoaderRoute: typeof ApiPublicPairStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ingest': {
      id: '/api/public/ingest'
      path: '/api/public/ingest'
      fullPath: '/api/public/ingest'
      preLoaderRoute: typeof ApiPublicIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/firmware-manifest': {
      id: '/api/public/firmware-manifest'
      path: '/api/public/firmware-manifest'
      fullPath: '/api/public/firmware-manifest'
      preLoaderRoute: typeof ApiPublicFirmwareManifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/config': {
      id: '/api/public/config'
      path: '/api/public/config'
      fullPath: '/api/public/config'
      preLoaderRoute: typeof ApiPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/claim': {
      id: '/api/public/claim'
      path: '/api/public/claim'
      fullPath: '/api/public/claim'
      preLoaderRoute: typeof ApiPublicClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sensors/new': {
      id: '/_authenticated/sensors/new'
      path: '/sensors/new'
      fullPath: '/sensors/new'
      preLoaderRoute: typeof AuthenticatedSensorsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sensors/$sensorId/edit': {
      id: '/_authenticated/sensors/$sensorId/edit'
      path: '/sensors/$sensorId/edit'
      fullPath: '/sensors/$sensorId/edit'
      preLoaderRoute: typeof AuthenticatedSensorsSensorIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/devices/$deviceId/register': {
      id: '/_authenticated/devices/$deviceId/register'
      path: '/$deviceId/register'
      fullPath: '/devices/$deviceId/register'
      preLoaderRoute: typeof AuthenticatedDevicesDeviceIdRegisterRouteImport
      parentRoute: typeof AuthenticatedDevicesRoute
    }
  }
}

interface AuthenticatedDevicesRouteChildren {
  AuthenticatedDevicesDeviceIdRegisterRoute: typeof AuthenticatedDevicesDeviceIdRegisterRoute
}

const AuthenticatedDevicesRouteChildren: AuthenticatedDevicesRouteChildren = {
  AuthenticatedDevicesDeviceIdRegisterRoute:
    AuthenticatedDevicesDeviceIdRegisterRoute,
}

const AuthenticatedDevicesRouteWithChildren =
  AuthenticatedDevicesRoute._addFileChildren(AuthenticatedDevicesRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDevicesRoute: typeof AuthenticatedDevicesRouteWithChildren
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedSensorsNewRoute: typeof AuthenticatedSensorsNewRoute
  AuthenticatedSensorsSensorIdEditRoute: typeof AuthenticatedSensorsSensorIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDevicesRoute: AuthenticatedDevicesRouteWithChildren,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedSensorsNewRoute: AuthenticatedSensorsNewRoute,
  AuthenticatedSensorsSensorIdEditRoute: AuthenticatedSensorsSensorIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicClaimRoute: ApiPublicClaimRoute,
  ApiPublicConfigRoute: ApiPublicConfigRoute,
  ApiPublicFirmwareManifestRoute: ApiPublicFirmwareManifestRoute,
  ApiPublicIngestRoute: ApiPublicIngestRoute,
  ApiPublicPairStatusRoute: ApiPublicPairStatusRoute,
  ApiPublicStateRoute: ApiPublicStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
